"""Added users1

Revision ID: 357f5da12cbf
Revises: 2ca7e358bce9
Create Date: 2014-11-02 22:55:23.659374

"""

# revision identifiers, used by Alembic.
revision = '357f5da12cbf'
down_revision = '2ca7e358bce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=50), nullable=True),
    sa.Column('psn', sa.String(length=50), nullable=True),
    sa.Column('github', sa.String(length=50), nullable=True),
    sa.Column('btc', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('tagline', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('avatar_normal', sa.String(length=50), nullable=True),
    sa.Column('user_created', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
