"""other table

Revision ID: 3e41ec180e5d
Revises: 357f5da12cbf
Create Date: 2014-11-03 00:16:48.460892

"""

# revision identifiers, used by Alembic.
revision = '3e41ec180e5d'
down_revision = '357f5da12cbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('title_alternative', sa.String(length=50), nullable=True),
    sa.Column('topics', sa.Integer(), nullable=True),
    sa.Column('header', sa.String(length=200), nullable=True),
    sa.Column('footer', sa.String(length=200), nullable=True),
    sa.Column('node_created', sa.DateTime(), nullable=True),
    sa.Column('avatar_normal', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nodeid')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('content_rendered', sa.String(length=1000), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('node', sa.Integer(), nullable=True),
    sa.Column('topic_created', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['node'], ['nodes.nodeid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topicid')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thanks', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('content_rendered', sa.String(length=1000), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('reply_created', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('topics')
    op.drop_table('nodes')
    ### end Alembic commands ###
